"""
Application Configuration — Updated with OAuth + Frontend URL settings
"""

from pydantic_settings import BaseSettings
from typing import Optional, List
import os


class Settings(BaseSettings):
    APP_NAME: str = "Fetch Ya Job"
    APP_VERSION: str = "1.0.0"
    DEBUG: bool = False

    DATABASE_URL: str = "sqlite:///./app.db"

    SECRET_KEY: Optional[str] = None
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 10080
    JWT_SECRET: Optional[str] = None
    JWT_ALGORITHM: Optional[str] = None
    JWT_EXPIRATION_DAYS: int = 7

    @property
    def secret_key(self) -> str:
        key = self.SECRET_KEY or self.JWT_SECRET
        if not key:
            raise ValueError(
                "JWT_SECRET / SECRET_KEY environment variable is not set. "
                "Generate with: python -c \"import secrets; print(secrets.token_hex(32))\""
            )
        return key

    @property
    def algorithm(self) -> str:
        return self.ALGORITHM or self.JWT_ALGORITHM or "HS256"

    # ── File Upload ────────────────────────────────────────
    UPLOAD_DIR: str = "./storage"
    MAX_UPLOAD_SIZE: Optional[int] = None
    MAX_FILE_SIZE: Optional[int] = None
    ALLOWED_EXTENSIONS: str = "pdf,docx,txt"
    DOWNLOADS_DIR: str = "./storage/downloads"
    MAX_BULK_DOWNLOAD: int = 50

    @property
    def max_upload_size(self) -> int:
        return self.MAX_UPLOAD_SIZE or self.MAX_FILE_SIZE or 10485760

    @property
    def allowed_extensions_list(self) -> List[str]:
        return [ext.strip().lower() for ext in self.ALLOWED_EXTENSIONS.split(",")]

    # ── Email ──────────────────────────────────────────────
    EMAIL_ENABLED: bool = False
    SMTP_ENABLED: bool = False
    SMTP_HOST: Optional[str] = "smtp.gmail.com"
    SMTP_PORT: int = 587
    SMTP_USER: Optional[str] = None
    SMTP_PASSWORD: Optional[str] = None
    SMTP_FROM: Optional[str] = None
    SMTP_FROM_EMAIL: Optional[str] = None
    SMTP_FROM_NAME: str = "Fetch Ya Job"

    @property
    def smtp_enabled(self) -> bool:
        return self.SMTP_ENABLED or self.EMAIL_ENABLED

    @property
    def smtp_from_email(self) -> str:
        return self.SMTP_FROM_EMAIL or self.SMTP_FROM or "noreply@fetchyajob.com"

    # ── CORS ───────────────────────────────────────────────
    CORS_ORIGINS: Optional[str] = None
    ALLOWED_ORIGINS: Optional[str] = None

    @property
    def cors_origins_list(self) -> List[str]:
        origins_str = self.CORS_ORIGINS or self.ALLOWED_ORIGINS or "http://localhost:80,http://localhost:5173"
        return [o.strip() for o in origins_str.split(",") if o.strip()]

    # ── Frontend URL (for OAuth redirects) ────────────────
    # In production: https://your-app.vercel.app
    # In development: http://localhost:5173
    FRONTEND_URL: str = "http://localhost:5173"

    # ── Google OAuth ───────────────────────────────────────
    GOOGLE_CLIENT_ID: Optional[str] = None
    GOOGLE_CLIENT_SECRET: Optional[str] = None
    GOOGLE_REDIRECT_URI: str = "http://localhost:8000/oauth/google/callback"

    # ── GitHub OAuth ───────────────────────────────────────
    GITHUB_CLIENT_ID: Optional[str] = None
    GITHUB_CLIENT_SECRET: Optional[str] = None
    GITHUB_REDIRECT_URI: str = "http://localhost:8000/oauth/github/callback"

    # ── Chat ───────────────────────────────────────────────
    CHAT_MESSAGE_LIMIT: int = 100
    CHAT_HISTORY_DAYS: int = 30

    # ── AI/ML ──────────────────────────────────────────────
    AI_SCORING_ENABLED: bool = True
    DEFAULT_SIMILARITY_THRESHOLD: float = 0.6
    DEFAULT_MIN_SCORE: float = 70.0
    DEFAULT_SCORE_THRESHOLD: float = 70.0
    DEFAULT_WEIGHTS: dict = {
        "skills_all": 25.0, "skills_any": 15.0,
        "experience": 15.0, "similarity": 20.0, "education": 25.0
    }

    REPORT_LOGO_PATH: Optional[str] = None
    REPORT_FOOTER_TEXT: str = "Generated by Fetch Ya Job AI System"

    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"
        case_sensitive = False


settings = Settings()


def get_upload_path(*paths: str) -> str:
    return os.path.join(settings.UPLOAD_DIR, *paths)


def get_download_path(*paths: str) -> str:
    return os.path.join(settings.DOWNLOADS_DIR, *paths)


def ensure_directories_exist():
    directories = [
        settings.UPLOAD_DIR, settings.DOWNLOADS_DIR,
        os.path.join(settings.UPLOAD_DIR, "jobs"),
        os.path.join(settings.UPLOAD_DIR, "downloads"),
        os.path.join(settings.UPLOAD_DIR, "temp"),
    ]
    for directory in directories:
        os.makedirs(directory, exist_ok=True)


def display_settings():
    print("\n" + "=" * 60)
    print("APPLICATION SETTINGS")
    print("=" * 60)
    db_safe = settings.DATABASE_URL.split("@")[-1] if "@" in settings.DATABASE_URL else settings.DATABASE_URL
    print(f"Database: {db_safe}")
    print(f"Debug: {settings.DEBUG}")
    print(f"CORS: {settings.cors_origins_list}")
    print(f"Frontend URL: {settings.FRONTEND_URL}")
    print(f"Google OAuth: {'configured' if settings.GOOGLE_CLIENT_ID else 'NOT SET'}")
    print(f"GitHub OAuth: {'configured' if settings.GITHUB_CLIENT_ID else 'NOT SET'}")
    print("=" * 60 + "\n")